# Generated by Django 5.1.4 on 2024-12-10 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('media', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), size=None)),
            ],
        ),
    ]
