# Generated by Django 5.1.4 on 2024-12-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='date',
            field=models.DateField(default='2024-10-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
