# Generated by Django 5.1.4 on 2024-12-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reflection_date_reflection_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reflection',
            old_name='title',
            new_name='name',
        ),
    ]
