# Generated by Django 5.1.4 on 2024-12-10 20:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_title_reflection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, null=True, size=None),
        ),
    ]
