# Generated by Django 5.1.4 on 2024-12-11 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_reflection_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('reaction', models.CharField(choices=[('L', 'Love'), ('H', 'Happy'), ('S', 'Sad'), ('C', 'Care')], default='L', max_length=1)),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.reflection')),
            ],
        ),
    ]
