# Generated by Django 5.1.4 on 2024-12-16 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_response_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='date',
        ),
        migrations.AddField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
